function cache = mv_lru_create(maxItems)
%MV_LRU_CREATE Create a tiny LRU cache struct.
    if nargin < 1 || isempty(maxItems)
        maxItems = 100;
    end
    cache = struct('maxItems', maxItems, ...
                   'map', containers.Map('KeyType','char','ValueType','any'), ...
                   'order', {{}}, ...
                   'hits', 0, ...
                   'misses', 0, ...
                   'evictions', 0);
end
